// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gqlgen-proto/options.proto

package gqlgen_proto

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MessageType int32

const (
	MessageType_UNKNOWN MessageType = 0
	MessageType_TYPE    MessageType = 1
	MessageType_INPUT   MessageType = 2
)

var MessageType_name = map[int32]string{
	0: "UNKNOWN",
	1: "TYPE",
	2: "INPUT",
}

var MessageType_value = map[string]int32{
	"UNKNOWN": 0,
	"TYPE":    1,
	"INPUT":   2,
}

func (x MessageType) String() string {
	return proto.EnumName(MessageType_name, int32(x))
}

func (MessageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_03469d44191f4235, []int{0}
}

type FileRule struct {
	TypeInference        []*InferrenceRule `protobuf:"bytes,1,rep,name=type_inference,json=typeInference,proto3" json:"type_inference,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *FileRule) Reset()         { *m = FileRule{} }
func (m *FileRule) String() string { return proto.CompactTextString(m) }
func (*FileRule) ProtoMessage()    {}
func (*FileRule) Descriptor() ([]byte, []int) {
	return fileDescriptor_03469d44191f4235, []int{0}
}

func (m *FileRule) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileRule.Unmarshal(m, b)
}
func (m *FileRule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileRule.Marshal(b, m, deterministic)
}
func (m *FileRule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileRule.Merge(m, src)
}
func (m *FileRule) XXX_Size() int {
	return xxx_messageInfo_FileRule.Size(m)
}
func (m *FileRule) XXX_DiscardUnknown() {
	xxx_messageInfo_FileRule.DiscardUnknown(m)
}

var xxx_messageInfo_FileRule proto.InternalMessageInfo

func (m *FileRule) GetTypeInference() []*InferrenceRule {
	if m != nil {
		return m.TypeInference
	}
	return nil
}

type InferrenceRule struct {
	Src                  string      `protobuf:"bytes,1,opt,name=src,proto3" json:"src,omitempty"`
	Dest                 string      `protobuf:"bytes,2,opt,name=dest,proto3" json:"dest,omitempty"`
	Type                 MessageType `protobuf:"varint,3,opt,name=type,proto3,enum=gqlgen.api.MessageType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *InferrenceRule) Reset()         { *m = InferrenceRule{} }
func (m *InferrenceRule) String() string { return proto.CompactTextString(m) }
func (*InferrenceRule) ProtoMessage()    {}
func (*InferrenceRule) Descriptor() ([]byte, []int) {
	return fileDescriptor_03469d44191f4235, []int{1}
}

func (m *InferrenceRule) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InferrenceRule.Unmarshal(m, b)
}
func (m *InferrenceRule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InferrenceRule.Marshal(b, m, deterministic)
}
func (m *InferrenceRule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InferrenceRule.Merge(m, src)
}
func (m *InferrenceRule) XXX_Size() int {
	return xxx_messageInfo_InferrenceRule.Size(m)
}
func (m *InferrenceRule) XXX_DiscardUnknown() {
	xxx_messageInfo_InferrenceRule.DiscardUnknown(m)
}

var xxx_messageInfo_InferrenceRule proto.InternalMessageInfo

func (m *InferrenceRule) GetSrc() string {
	if m != nil {
		return m.Src
	}
	return ""
}

func (m *InferrenceRule) GetDest() string {
	if m != nil {
		return m.Dest
	}
	return ""
}

func (m *InferrenceRule) GetType() MessageType {
	if m != nil {
		return m.Type
	}
	return MessageType_UNKNOWN
}

type SchemaRule struct {
	// Types that are valid to be assigned to Pattern:
	//	*SchemaRule_Query
	//	*SchemaRule_Mutation
	//	*SchemaRule_Subscription
	Pattern              isSchemaRule_Pattern `protobuf_oneof:"pattern"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *SchemaRule) Reset()         { *m = SchemaRule{} }
func (m *SchemaRule) String() string { return proto.CompactTextString(m) }
func (*SchemaRule) ProtoMessage()    {}
func (*SchemaRule) Descriptor() ([]byte, []int) {
	return fileDescriptor_03469d44191f4235, []int{2}
}

func (m *SchemaRule) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SchemaRule.Unmarshal(m, b)
}
func (m *SchemaRule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SchemaRule.Marshal(b, m, deterministic)
}
func (m *SchemaRule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SchemaRule.Merge(m, src)
}
func (m *SchemaRule) XXX_Size() int {
	return xxx_messageInfo_SchemaRule.Size(m)
}
func (m *SchemaRule) XXX_DiscardUnknown() {
	xxx_messageInfo_SchemaRule.DiscardUnknown(m)
}

var xxx_messageInfo_SchemaRule proto.InternalMessageInfo

type isSchemaRule_Pattern interface {
	isSchemaRule_Pattern()
}

type SchemaRule_Query struct {
	Query string `protobuf:"bytes,1,opt,name=query,proto3,oneof"`
}

type SchemaRule_Mutation struct {
	Mutation string `protobuf:"bytes,2,opt,name=mutation,proto3,oneof"`
}

type SchemaRule_Subscription struct {
	Subscription string `protobuf:"bytes,3,opt,name=subscription,proto3,oneof"`
}

func (*SchemaRule_Query) isSchemaRule_Pattern() {}

func (*SchemaRule_Mutation) isSchemaRule_Pattern() {}

func (*SchemaRule_Subscription) isSchemaRule_Pattern() {}

func (m *SchemaRule) GetPattern() isSchemaRule_Pattern {
	if m != nil {
		return m.Pattern
	}
	return nil
}

func (m *SchemaRule) GetQuery() string {
	if x, ok := m.GetPattern().(*SchemaRule_Query); ok {
		return x.Query
	}
	return ""
}

func (m *SchemaRule) GetMutation() string {
	if x, ok := m.GetPattern().(*SchemaRule_Mutation); ok {
		return x.Mutation
	}
	return ""
}

func (m *SchemaRule) GetSubscription() string {
	if x, ok := m.GetPattern().(*SchemaRule_Subscription); ok {
		return x.Subscription
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*SchemaRule) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*SchemaRule_Query)(nil),
		(*SchemaRule_Mutation)(nil),
		(*SchemaRule_Subscription)(nil),
	}
}

type MessageRule struct {
	Alias                string      `protobuf:"bytes,1,opt,name=alias,proto3" json:"alias,omitempty"`
	Type                 MessageType `protobuf:"varint,2,opt,name=type,proto3,enum=gqlgen.api.MessageType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *MessageRule) Reset()         { *m = MessageRule{} }
func (m *MessageRule) String() string { return proto.CompactTextString(m) }
func (*MessageRule) ProtoMessage()    {}
func (*MessageRule) Descriptor() ([]byte, []int) {
	return fileDescriptor_03469d44191f4235, []int{3}
}

func (m *MessageRule) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageRule.Unmarshal(m, b)
}
func (m *MessageRule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageRule.Marshal(b, m, deterministic)
}
func (m *MessageRule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageRule.Merge(m, src)
}
func (m *MessageRule) XXX_Size() int {
	return xxx_messageInfo_MessageRule.Size(m)
}
func (m *MessageRule) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageRule.DiscardUnknown(m)
}

var xxx_messageInfo_MessageRule proto.InternalMessageInfo

func (m *MessageRule) GetAlias() string {
	if m != nil {
		return m.Alias
	}
	return ""
}

func (m *MessageRule) GetType() MessageType {
	if m != nil {
		return m.Type
	}
	return MessageType_UNKNOWN
}

type FieldRule struct {
	Alias                string   `protobuf:"bytes,1,opt,name=alias,proto3" json:"alias,omitempty"`
	Optional             bool     `protobuf:"varint,2,opt,name=optional,proto3" json:"optional,omitempty"`
	Id                   bool     `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FieldRule) Reset()         { *m = FieldRule{} }
func (m *FieldRule) String() string { return proto.CompactTextString(m) }
func (*FieldRule) ProtoMessage()    {}
func (*FieldRule) Descriptor() ([]byte, []int) {
	return fileDescriptor_03469d44191f4235, []int{4}
}

func (m *FieldRule) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FieldRule.Unmarshal(m, b)
}
func (m *FieldRule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FieldRule.Marshal(b, m, deterministic)
}
func (m *FieldRule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FieldRule.Merge(m, src)
}
func (m *FieldRule) XXX_Size() int {
	return xxx_messageInfo_FieldRule.Size(m)
}
func (m *FieldRule) XXX_DiscardUnknown() {
	xxx_messageInfo_FieldRule.DiscardUnknown(m)
}

var xxx_messageInfo_FieldRule proto.InternalMessageInfo

func (m *FieldRule) GetAlias() string {
	if m != nil {
		return m.Alias
	}
	return ""
}

func (m *FieldRule) GetOptional() bool {
	if m != nil {
		return m.Optional
	}
	return false
}

func (m *FieldRule) GetId() bool {
	if m != nil {
		return m.Id
	}
	return false
}

type EnumRule struct {
	Alias                string   `protobuf:"bytes,1,opt,name=alias,proto3" json:"alias,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnumRule) Reset()         { *m = EnumRule{} }
func (m *EnumRule) String() string { return proto.CompactTextString(m) }
func (*EnumRule) ProtoMessage()    {}
func (*EnumRule) Descriptor() ([]byte, []int) {
	return fileDescriptor_03469d44191f4235, []int{5}
}

func (m *EnumRule) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnumRule.Unmarshal(m, b)
}
func (m *EnumRule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnumRule.Marshal(b, m, deterministic)
}
func (m *EnumRule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnumRule.Merge(m, src)
}
func (m *EnumRule) XXX_Size() int {
	return xxx_messageInfo_EnumRule.Size(m)
}
func (m *EnumRule) XXX_DiscardUnknown() {
	xxx_messageInfo_EnumRule.DiscardUnknown(m)
}

var xxx_messageInfo_EnumRule proto.InternalMessageInfo

func (m *EnumRule) GetAlias() string {
	if m != nil {
		return m.Alias
	}
	return ""
}

type EnumValueRule struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnumValueRule) Reset()         { *m = EnumValueRule{} }
func (m *EnumValueRule) String() string { return proto.CompactTextString(m) }
func (*EnumValueRule) ProtoMessage()    {}
func (*EnumValueRule) Descriptor() ([]byte, []int) {
	return fileDescriptor_03469d44191f4235, []int{6}
}

func (m *EnumValueRule) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnumValueRule.Unmarshal(m, b)
}
func (m *EnumValueRule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnumValueRule.Marshal(b, m, deterministic)
}
func (m *EnumValueRule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnumValueRule.Merge(m, src)
}
func (m *EnumValueRule) XXX_Size() int {
	return xxx_messageInfo_EnumValueRule.Size(m)
}
func (m *EnumValueRule) XXX_DiscardUnknown() {
	xxx_messageInfo_EnumValueRule.DiscardUnknown(m)
}

var xxx_messageInfo_EnumValueRule proto.InternalMessageInfo

var E_Resolver = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*FileRule)(nil),
	Field:         50000,
	Name:          "gqlgen.api.resolver",
	Tag:           "bytes,50000,opt,name=resolver",
	Filename:      "gqlgen-proto/options.proto",
}

var E_Schema = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MethodOptions)(nil),
	ExtensionType: (*SchemaRule)(nil),
	Field:         50001,
	Name:          "gqlgen.api.schema",
	Tag:           "bytes,50001,opt,name=schema",
	Filename:      "gqlgen-proto/options.proto",
}

var E_Type = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*MessageRule)(nil),
	Field:         50002,
	Name:          "gqlgen.api.type",
	Tag:           "bytes,50002,opt,name=type",
	Filename:      "gqlgen-proto/options.proto",
}

var E_Field = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*FieldRule)(nil),
	Field:         50003,
	Name:          "gqlgen.api.field",
	Tag:           "bytes,50003,opt,name=field",
	Filename:      "gqlgen-proto/options.proto",
}

var E_Enum = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.EnumOptions)(nil),
	ExtensionType: (*EnumRule)(nil),
	Field:         50004,
	Name:          "gqlgen.api.enum",
	Tag:           "bytes,50004,opt,name=enum",
	Filename:      "gqlgen-proto/options.proto",
}

var E_EnumValue = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.EnumValueOptions)(nil),
	ExtensionType: (*EnumValueRule)(nil),
	Field:         50005,
	Name:          "gqlgen.api.enum_value",
	Tag:           "bytes,50005,opt,name=enum_value",
	Filename:      "gqlgen-proto/options.proto",
}

func init() {
	proto.RegisterEnum("gqlgen.api.MessageType", MessageType_name, MessageType_value)
	proto.RegisterType((*FileRule)(nil), "gqlgen.api.FileRule")
	proto.RegisterType((*InferrenceRule)(nil), "gqlgen.api.InferrenceRule")
	proto.RegisterType((*SchemaRule)(nil), "gqlgen.api.SchemaRule")
	proto.RegisterType((*MessageRule)(nil), "gqlgen.api.MessageRule")
	proto.RegisterType((*FieldRule)(nil), "gqlgen.api.FieldRule")
	proto.RegisterType((*EnumRule)(nil), "gqlgen.api.EnumRule")
	proto.RegisterType((*EnumValueRule)(nil), "gqlgen.api.EnumValueRule")
	proto.RegisterExtension(E_Resolver)
	proto.RegisterExtension(E_Schema)
	proto.RegisterExtension(E_Type)
	proto.RegisterExtension(E_Field)
	proto.RegisterExtension(E_Enum)
	proto.RegisterExtension(E_EnumValue)
}

func init() { proto.RegisterFile("gqlgen-proto/options.proto", fileDescriptor_03469d44191f4235) }

var fileDescriptor_03469d44191f4235 = []byte{
	// 586 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x94, 0x59, 0x6f, 0xd3, 0x40,
	0x10, 0xc7, 0x73, 0xb6, 0xce, 0x84, 0x86, 0x68, 0x55, 0x4a, 0x88, 0x0a, 0x04, 0x8b, 0x87, 0x08,
	0x54, 0x5b, 0x0a, 0x6f, 0xe6, 0xa9, 0x45, 0xad, 0x12, 0x41, 0xd2, 0x68, 0x49, 0x41, 0x20, 0xa1,
	0xc8, 0xb1, 0x27, 0x8e, 0x85, 0xaf, 0xfa, 0x88, 0x94, 0x2f, 0xc0, 0xe7, 0xe3, 0xfc, 0x3e, 0x68,
	0x77, 0x6d, 0x37, 0x01, 0x83, 0xfa, 0x12, 0xef, 0xec, 0xcc, 0xfe, 0xe6, 0xf8, 0x8f, 0x02, 0x5d,
	0xeb, 0xda, 0xb1, 0xd0, 0x3b, 0x09, 0x42, 0x3f, 0xf6, 0x55, 0x3f, 0x88, 0x6d, 0xdf, 0x8b, 0x14,
	0x6e, 0x11, 0x10, 0x3e, 0x45, 0x0f, 0xec, 0x6e, 0xcf, 0xf2, 0x7d, 0xcb, 0x41, 0x95, 0x7b, 0x16,
	0xc9, 0x52, 0x35, 0x31, 0x32, 0x42, 0x3b, 0x88, 0xfd, 0x50, 0x44, 0xcb, 0x63, 0x90, 0x2e, 0x6c,
	0x07, 0x69, 0xe2, 0x20, 0x39, 0x85, 0x56, 0xbc, 0x09, 0x70, 0x6e, 0x7b, 0x4b, 0x0c, 0xd1, 0x33,
	0xb0, 0x53, 0xee, 0x55, 0xfb, 0xcd, 0x41, 0x57, 0xb9, 0x41, 0x2a, 0x23, 0xe6, 0xe4, 0x5e, 0xf6,
	0x86, 0x1e, 0xb0, 0x17, 0xa3, 0xec, 0x81, 0x6c, 0x40, 0x6b, 0x37, 0x80, 0xb4, 0xa1, 0x1a, 0x85,
	0x46, 0xa7, 0xdc, 0x2b, 0xf7, 0x1b, 0x94, 0x1d, 0x09, 0x81, 0x9a, 0x89, 0x51, 0xdc, 0xa9, 0xf0,
	0x2b, 0x7e, 0x26, 0xcf, 0xa1, 0xc6, 0x40, 0x9d, 0x6a, 0xaf, 0xdc, 0x6f, 0x0d, 0xee, 0x6f, 0x27,
	0x1c, 0x63, 0x14, 0xe9, 0x16, 0xce, 0x36, 0x01, 0x52, 0x1e, 0x24, 0x47, 0x00, 0x6f, 0x8d, 0x15,
	0xba, 0x3a, 0x4f, 0x70, 0x04, 0xf5, 0xeb, 0x04, 0xc3, 0x8d, 0x48, 0x31, 0x2c, 0x51, 0x61, 0x92,
	0x63, 0x90, 0xdc, 0x24, 0xd6, 0xd9, 0x68, 0x44, 0xaa, 0x61, 0x89, 0xe6, 0x37, 0xe4, 0x29, 0xdc,
	0x89, 0x92, 0x85, 0x18, 0x06, 0x8b, 0xa8, 0xa6, 0x11, 0x3b, 0xb7, 0x67, 0x0d, 0xd8, 0x0f, 0xf4,
	0x38, 0xc6, 0xd0, 0x93, 0xa7, 0xd0, 0x4c, 0x2b, 0xe1, 0x59, 0x0f, 0xa1, 0xae, 0x3b, 0xb6, 0x1e,
	0xa5, 0x8d, 0x09, 0x23, 0x6f, 0xa3, 0x72, 0x9b, 0x36, 0xc6, 0xd0, 0xb8, 0xb0, 0xd1, 0x31, 0xff,
	0xc3, 0xeb, 0x82, 0x24, 0xc4, 0xd5, 0x1d, 0xce, 0x94, 0x68, 0x6e, 0x93, 0x16, 0x54, 0x6c, 0x93,
	0xd7, 0x2d, 0xd1, 0x8a, 0x6d, 0xca, 0x3d, 0x90, 0xce, 0xbd, 0xc4, 0xfd, 0x37, 0x4d, 0xbe, 0x0b,
	0x07, 0x2c, 0xe2, 0x9d, 0xee, 0x24, 0xbc, 0x89, 0x67, 0x6a, 0xde, 0x13, 0x2b, 0x8b, 0x34, 0x61,
	0xff, 0x6a, 0xf2, 0x7a, 0x72, 0xf9, 0x7e, 0xd2, 0x2e, 0x11, 0x09, 0x6a, 0xb3, 0x0f, 0xd3, 0xf3,
	0x76, 0x99, 0x34, 0xa0, 0x3e, 0x9a, 0x4c, 0xaf, 0x66, 0xed, 0x8a, 0x36, 0x05, 0x29, 0xc4, 0xc8,
	0x77, 0xd6, 0x18, 0x92, 0x63, 0x45, 0x2c, 0x97, 0x92, 0x2d, 0x97, 0xc2, 0x16, 0xe9, 0x52, 0xec,
	0x62, 0xe7, 0xeb, 0x17, 0x56, 0x59, 0x73, 0x70, 0xb8, 0x3d, 0x83, 0x6c, 0xd3, 0x68, 0x4e, 0xd1,
	0xa6, 0xb0, 0x17, 0x71, 0x2d, 0xc9, 0xa3, 0xbf, 0x78, 0x63, 0x8c, 0x57, 0xbe, 0x99, 0x11, 0xbf,
	0xa5, 0xc4, 0xa3, 0x6d, 0xe2, 0xcd, 0x1e, 0xd0, 0x94, 0xa3, 0x4d, 0x84, 0x06, 0xe4, 0x71, 0x01,
	0x8f, 0xf7, 0x9a, 0x01, 0xbf, 0xa7, 0xc0, 0x22, 0x99, 0x38, 0x91, 0x73, 0xb4, 0x37, 0x50, 0x5f,
	0x32, 0x99, 0xc8, 0xc3, 0x82, 0x86, 0xd1, 0xc9, 0xeb, 0xfb, 0x91, 0xe2, 0xee, 0xed, 0x76, 0x9c,
	0x0a, 0x4c, 0x05, 0x44, 0x1b, 0x42, 0x0d, 0xbd, 0xc4, 0x2d, 0x98, 0x1e, 0x93, 0x26, 0x63, 0xfd,
	0x2c, 0x9a, 0x5e, 0xa6, 0x2e, 0xe5, 0x04, 0xed, 0x13, 0x00, 0xfb, 0xce, 0xd7, 0x4c, 0x4e, 0xf2,
	0xa4, 0x90, 0xc7, 0xa5, 0xce, 0xa0, 0xbf, 0x52, 0xe8, 0x83, 0x3f, 0xa1, 0xf9, 0x42, 0xd0, 0x06,
	0x66, 0xe6, 0xd9, 0xab, 0x8f, 0xa7, 0x96, 0x1d, 0xaf, 0x92, 0x85, 0x62, 0xf8, 0xae, 0xba, 0x5e,
	0xeb, 0x9f, 0x75, 0x17, 0xd5, 0xd8, 0x76, 0x54, 0x2b, 0x0c, 0x0c, 0xfe, 0x73, 0x22, 0x38, 0xea,
	0xf6, 0x9f, 0xd1, 0x4b, 0x61, 0xcc, 0x45, 0x19, 0x7b, 0xfc, 0xf3, 0xe2, 0x77, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x6a, 0x06, 0xda, 0xd8, 0xb0, 0x04, 0x00, 0x00,
}
