// Code generated by protoc-gen-go. DO NOT EDIT.
// source: microservices/user/user.proto

package user

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Noop struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Noop) Reset()         { *m = Noop{} }
func (m *Noop) String() string { return proto.CompactTextString(m) }
func (*Noop) ProtoMessage()    {}
func (*Noop) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b07f94b78421c3d, []int{0}
}

func (m *Noop) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Noop.Unmarshal(m, b)
}
func (m *Noop) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Noop.Marshal(b, m, deterministic)
}
func (m *Noop) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Noop.Merge(m, src)
}
func (m *Noop) XXX_Size() int {
	return xxx_messageInfo_Noop.Size(m)
}
func (m *Noop) XXX_DiscardUnknown() {
	xxx_messageInfo_Noop.DiscardUnknown(m)
}

var xxx_messageInfo_Noop proto.InternalMessageInfo

type User struct {
	UserId               uint64               `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserName             string               `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Email                string               `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b07f94b78421c3d, []int{1}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetUserId() uint64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *User) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *User) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

type SignUpRequest struct {
	UserName             string   `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignUpRequest) Reset()         { *m = SignUpRequest{} }
func (m *SignUpRequest) String() string { return proto.CompactTextString(m) }
func (*SignUpRequest) ProtoMessage()    {}
func (*SignUpRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b07f94b78421c3d, []int{2}
}

func (m *SignUpRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignUpRequest.Unmarshal(m, b)
}
func (m *SignUpRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignUpRequest.Marshal(b, m, deterministic)
}
func (m *SignUpRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignUpRequest.Merge(m, src)
}
func (m *SignUpRequest) XXX_Size() int {
	return xxx_messageInfo_SignUpRequest.Size(m)
}
func (m *SignUpRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignUpRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignUpRequest proto.InternalMessageInfo

func (m *SignUpRequest) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *SignUpRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *SignUpRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type SignUpResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignUpResponse) Reset()         { *m = SignUpResponse{} }
func (m *SignUpResponse) String() string { return proto.CompactTextString(m) }
func (*SignUpResponse) ProtoMessage()    {}
func (*SignUpResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b07f94b78421c3d, []int{3}
}

func (m *SignUpResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignUpResponse.Unmarshal(m, b)
}
func (m *SignUpResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignUpResponse.Marshal(b, m, deterministic)
}
func (m *SignUpResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignUpResponse.Merge(m, src)
}
func (m *SignUpResponse) XXX_Size() int {
	return xxx_messageInfo_SignUpResponse.Size(m)
}
func (m *SignUpResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SignUpResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SignUpResponse proto.InternalMessageInfo

func (m *SignUpResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type SignInRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignInRequest) Reset()         { *m = SignInRequest{} }
func (m *SignInRequest) String() string { return proto.CompactTextString(m) }
func (*SignInRequest) ProtoMessage()    {}
func (*SignInRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b07f94b78421c3d, []int{4}
}

func (m *SignInRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignInRequest.Unmarshal(m, b)
}
func (m *SignInRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignInRequest.Marshal(b, m, deterministic)
}
func (m *SignInRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignInRequest.Merge(m, src)
}
func (m *SignInRequest) XXX_Size() int {
	return xxx_messageInfo_SignInRequest.Size(m)
}
func (m *SignInRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignInRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignInRequest proto.InternalMessageInfo

func (m *SignInRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *SignInRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type SignInResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignInResponse) Reset()         { *m = SignInResponse{} }
func (m *SignInResponse) String() string { return proto.CompactTextString(m) }
func (*SignInResponse) ProtoMessage()    {}
func (*SignInResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b07f94b78421c3d, []int{5}
}

func (m *SignInResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignInResponse.Unmarshal(m, b)
}
func (m *SignInResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignInResponse.Marshal(b, m, deterministic)
}
func (m *SignInResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignInResponse.Merge(m, src)
}
func (m *SignInResponse) XXX_Size() int {
	return xxx_messageInfo_SignInResponse.Size(m)
}
func (m *SignInResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SignInResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SignInResponse proto.InternalMessageInfo

func (m *SignInResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type SignOutRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignOutRequest) Reset()         { *m = SignOutRequest{} }
func (m *SignOutRequest) String() string { return proto.CompactTextString(m) }
func (*SignOutRequest) ProtoMessage()    {}
func (*SignOutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b07f94b78421c3d, []int{6}
}

func (m *SignOutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignOutRequest.Unmarshal(m, b)
}
func (m *SignOutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignOutRequest.Marshal(b, m, deterministic)
}
func (m *SignOutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignOutRequest.Merge(m, src)
}
func (m *SignOutRequest) XXX_Size() int {
	return xxx_messageInfo_SignOutRequest.Size(m)
}
func (m *SignOutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignOutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignOutRequest proto.InternalMessageInfo

type SignOutResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignOutResponse) Reset()         { *m = SignOutResponse{} }
func (m *SignOutResponse) String() string { return proto.CompactTextString(m) }
func (*SignOutResponse) ProtoMessage()    {}
func (*SignOutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b07f94b78421c3d, []int{7}
}

func (m *SignOutResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignOutResponse.Unmarshal(m, b)
}
func (m *SignOutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignOutResponse.Marshal(b, m, deterministic)
}
func (m *SignOutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignOutResponse.Merge(m, src)
}
func (m *SignOutResponse) XXX_Size() int {
	return xxx_messageInfo_SignOutResponse.Size(m)
}
func (m *SignOutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SignOutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SignOutResponse proto.InternalMessageInfo

type ViewerRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ViewerRequest) Reset()         { *m = ViewerRequest{} }
func (m *ViewerRequest) String() string { return proto.CompactTextString(m) }
func (*ViewerRequest) ProtoMessage()    {}
func (*ViewerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b07f94b78421c3d, []int{8}
}

func (m *ViewerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ViewerRequest.Unmarshal(m, b)
}
func (m *ViewerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ViewerRequest.Marshal(b, m, deterministic)
}
func (m *ViewerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ViewerRequest.Merge(m, src)
}
func (m *ViewerRequest) XXX_Size() int {
	return xxx_messageInfo_ViewerRequest.Size(m)
}
func (m *ViewerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ViewerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ViewerRequest proto.InternalMessageInfo

type ViewerResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ViewerResponse) Reset()         { *m = ViewerResponse{} }
func (m *ViewerResponse) String() string { return proto.CompactTextString(m) }
func (*ViewerResponse) ProtoMessage()    {}
func (*ViewerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b07f94b78421c3d, []int{9}
}

func (m *ViewerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ViewerResponse.Unmarshal(m, b)
}
func (m *ViewerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ViewerResponse.Marshal(b, m, deterministic)
}
func (m *ViewerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ViewerResponse.Merge(m, src)
}
func (m *ViewerResponse) XXX_Size() int {
	return xxx_messageInfo_ViewerResponse.Size(m)
}
func (m *ViewerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ViewerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ViewerResponse proto.InternalMessageInfo

func (m *ViewerResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type GetUserByIdRequest struct {
	UserId               uint64   `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserByIdRequest) Reset()         { *m = GetUserByIdRequest{} }
func (m *GetUserByIdRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserByIdRequest) ProtoMessage()    {}
func (*GetUserByIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b07f94b78421c3d, []int{10}
}

func (m *GetUserByIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserByIdRequest.Unmarshal(m, b)
}
func (m *GetUserByIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserByIdRequest.Marshal(b, m, deterministic)
}
func (m *GetUserByIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserByIdRequest.Merge(m, src)
}
func (m *GetUserByIdRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserByIdRequest.Size(m)
}
func (m *GetUserByIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserByIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserByIdRequest proto.InternalMessageInfo

func (m *GetUserByIdRequest) GetUserId() uint64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type GetUserByIdResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserByIdResponse) Reset()         { *m = GetUserByIdResponse{} }
func (m *GetUserByIdResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserByIdResponse) ProtoMessage()    {}
func (*GetUserByIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b07f94b78421c3d, []int{11}
}

func (m *GetUserByIdResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserByIdResponse.Unmarshal(m, b)
}
func (m *GetUserByIdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserByIdResponse.Marshal(b, m, deterministic)
}
func (m *GetUserByIdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserByIdResponse.Merge(m, src)
}
func (m *GetUserByIdResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserByIdResponse.Size(m)
}
func (m *GetUserByIdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserByIdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserByIdResponse proto.InternalMessageInfo

func (m *GetUserByIdResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type UpdateUserRequest struct {
	UserName             string   `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserRequest) Reset()         { *m = UpdateUserRequest{} }
func (m *UpdateUserRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateUserRequest) ProtoMessage()    {}
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b07f94b78421c3d, []int{12}
}

func (m *UpdateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserRequest.Unmarshal(m, b)
}
func (m *UpdateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserRequest.Marshal(b, m, deterministic)
}
func (m *UpdateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserRequest.Merge(m, src)
}
func (m *UpdateUserRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateUserRequest.Size(m)
}
func (m *UpdateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserRequest proto.InternalMessageInfo

func (m *UpdateUserRequest) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *UpdateUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type UpdateUserResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserResponse) Reset()         { *m = UpdateUserResponse{} }
func (m *UpdateUserResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateUserResponse) ProtoMessage()    {}
func (*UpdateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b07f94b78421c3d, []int{13}
}

func (m *UpdateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserResponse.Unmarshal(m, b)
}
func (m *UpdateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserResponse.Marshal(b, m, deterministic)
}
func (m *UpdateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserResponse.Merge(m, src)
}
func (m *UpdateUserResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateUserResponse.Size(m)
}
func (m *UpdateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserResponse proto.InternalMessageInfo

func (m *UpdateUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func init() {
	proto.RegisterType((*Noop)(nil), "microservices.user.Noop")
	proto.RegisterType((*User)(nil), "microservices.user.User")
	proto.RegisterType((*SignUpRequest)(nil), "microservices.user.SignUpRequest")
	proto.RegisterType((*SignUpResponse)(nil), "microservices.user.SignUpResponse")
	proto.RegisterType((*SignInRequest)(nil), "microservices.user.SignInRequest")
	proto.RegisterType((*SignInResponse)(nil), "microservices.user.SignInResponse")
	proto.RegisterType((*SignOutRequest)(nil), "microservices.user.SignOutRequest")
	proto.RegisterType((*SignOutResponse)(nil), "microservices.user.SignOutResponse")
	proto.RegisterType((*ViewerRequest)(nil), "microservices.user.ViewerRequest")
	proto.RegisterType((*ViewerResponse)(nil), "microservices.user.ViewerResponse")
	proto.RegisterType((*GetUserByIdRequest)(nil), "microservices.user.GetUserByIdRequest")
	proto.RegisterType((*GetUserByIdResponse)(nil), "microservices.user.GetUserByIdResponse")
	proto.RegisterType((*UpdateUserRequest)(nil), "microservices.user.UpdateUserRequest")
	proto.RegisterType((*UpdateUserResponse)(nil), "microservices.user.UpdateUserResponse")
}

func init() { proto.RegisterFile("microservices/user/user.proto", fileDescriptor_0b07f94b78421c3d) }

var fileDescriptor_0b07f94b78421c3d = []byte{
	// 522 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x94, 0xd1, 0x6a, 0xdb, 0x3e,
	0x18, 0xc5, 0x71, 0xfe, 0x6e, 0xda, 0x7c, 0xa1, 0xed, 0xbf, 0xda, 0x60, 0xc1, 0x63, 0x2c, 0xd3,
	0x58, 0x97, 0x8b, 0xd5, 0x86, 0xec, 0x6a, 0x63, 0x14, 0x92, 0xc1, 0x46, 0x6e, 0x5a, 0x70, 0x97,
	0x5d, 0x6c, 0xd0, 0xe2, 0xc4, 0xdf, 0x3c, 0xb3, 0xd8, 0x72, 0x2d, 0x39, 0x65, 0x8f, 0xb1, 0xb7,
	0xda, 0x63, 0x0d, 0x49, 0x76, 0x12, 0x37, 0x76, 0x03, 0xbe, 0x31, 0xe8, 0xd3, 0x39, 0xc7, 0x3f,
	0x5b, 0x07, 0xc1, 0xb3, 0x28, 0x9c, 0xa7, 0x8c, 0x63, 0xba, 0x0c, 0xe7, 0xc8, 0x9d, 0x8c, 0x63,
	0xaa, 0x1e, 0x76, 0x92, 0x32, 0xc1, 0x08, 0x29, 0x6d, 0xdb, 0x72, 0xc7, 0x7a, 0x1e, 0x30, 0x16,
	0x2c, 0xd0, 0x51, 0x8a, 0x59, 0xf6, 0xc3, 0x11, 0x61, 0x84, 0x5c, 0x78, 0x51, 0xa2, 0x4d, 0xb4,
	0x0d, 0xe6, 0x05, 0x63, 0x09, 0xfd, 0x6b, 0x80, 0x39, 0xe5, 0x98, 0x92, 0x27, 0xb0, 0x2f, 0x9d,
	0x37, 0xa1, 0xdf, 0x33, 0xfa, 0xc6, 0xc0, 0x74, 0xdb, 0x72, 0x39, 0xf1, 0xc9, 0x53, 0xe8, 0xa8,
	0x8d, 0xd8, 0x8b, 0xb0, 0xd7, 0xea, 0x1b, 0x83, 0x8e, 0x7b, 0x20, 0x07, 0x17, 0x5e, 0x84, 0xe4,
	0x31, 0xec, 0x61, 0xe4, 0x85, 0x8b, 0xde, 0x7f, 0x6a, 0x43, 0x2f, 0xc8, 0x3b, 0x80, 0x2c, 0xf1,
	0x3d, 0x81, 0xfe, 0x8d, 0x27, 0x7a, 0x66, 0xdf, 0x18, 0x74, 0x87, 0x96, 0xad, 0x91, 0xec, 0x02,
	0xc9, 0xfe, 0x52, 0x20, 0xb9, 0x9d, 0x5c, 0x3d, 0x12, 0xd2, 0x3a, 0x4f, 0xb1, 0xb0, 0xee, 0xed,
	0xb6, 0xe6, 0xea, 0x91, 0xa0, 0xd7, 0x70, 0x78, 0x15, 0x06, 0xf1, 0x34, 0x71, 0xf1, 0x36, 0x43,
	0x2e, 0xca, 0xe4, 0x46, 0x1d, 0x79, 0x6b, 0x93, 0xdc, 0x82, 0x83, 0xc4, 0xe3, 0xfc, 0x8e, 0xa5,
	0x7e, 0xfe, 0x49, 0xab, 0x35, 0x3d, 0x87, 0xa3, 0x22, 0x9f, 0x27, 0x2c, 0xe6, 0x48, 0xde, 0x80,
	0x29, 0xf3, 0x54, 0x76, 0x77, 0xd8, 0xb3, 0xb7, 0x0f, 0xc2, 0x96, 0xff, 0xd6, 0x55, 0x2a, 0x3a,
	0xd2, 0x7c, 0x93, 0xb8, 0xe0, 0x5b, 0x21, 0x18, 0x75, 0x08, 0xad, 0x6a, 0x04, 0x19, 0xd1, 0x08,
	0xe1, 0x7f, 0xed, 0xbf, 0xcc, 0x44, 0xce, 0x40, 0x4f, 0xe0, 0x78, 0x35, 0xd1, 0x91, 0xf4, 0x18,
	0x0e, 0xbf, 0x86, 0x78, 0x87, 0x69, 0xa1, 0x39, 0x87, 0xa3, 0x62, 0xd0, 0xe8, 0xad, 0x67, 0x40,
	0x3e, 0xa3, 0x90, 0x83, 0xf1, 0xef, 0x89, 0x5f, 0x7c, 0x7d, 0x5d, 0xe1, 0xe8, 0x47, 0x78, 0x54,
	0x92, 0x37, 0x7a, 0xe7, 0x27, 0x38, 0x99, 0xaa, 0x52, 0xa9, 0x59, 0xe3, 0x42, 0xd0, 0x31, 0x90,
	0xcd, 0x9c, 0x26, 0x2c, 0xc3, 0x3f, 0x26, 0x74, 0xe5, 0xf2, 0x4a, 0x0b, 0xc8, 0x25, 0xb4, 0x75,
	0x91, 0xc8, 0x8b, 0x2a, 0x67, 0xa9, 0xc4, 0x16, 0x7d, 0x48, 0x92, 0xe3, 0xe4, 0x81, 0x93, 0xb8,
	0x3e, 0x70, 0xd5, 0xba, 0xfa, 0xc0, 0x8d, 0x56, 0xb9, 0xb0, 0x9f, 0xb7, 0x82, 0xd4, 0xca, 0xd7,
	0x25, 0xb2, 0x5e, 0x3e, 0xa8, 0x59, 0x43, 0xea, 0x16, 0x55, 0x43, 0x96, 0x2a, 0x57, 0x0d, 0x79,
	0xaf, 0x84, 0xd7, 0xd0, 0xdd, 0xe8, 0x09, 0x39, 0xad, 0xb2, 0x6c, 0xf7, 0xce, 0x7a, 0xbd, 0x53,
	0x97, 0xe7, 0x7f, 0x07, 0x58, 0x1f, 0x3d, 0x79, 0x55, 0x79, 0xc8, 0xf7, 0x2b, 0x66, 0x9d, 0xee,
	0x92, 0xe9, 0xf0, 0xf1, 0x87, 0x6f, 0xef, 0x83, 0x50, 0xfc, 0xcc, 0x66, 0xf6, 0x9c, 0x45, 0xce,
	0x72, 0xe9, 0xfd, 0xf2, 0x22, 0x74, 0x44, 0xb8, 0x70, 0x82, 0x34, 0x99, 0xab, 0xc7, 0x59, 0x70,
	0xbb, 0x08, 0x30, 0x76, 0xb6, 0x6f, 0xff, 0x59, 0x5b, 0xdd, 0x84, 0x6f, 0xff, 0x05, 0x00, 0x00,
	0xff, 0xff, 0xaa, 0xf5, 0x11, 0xbd, 0x1a, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	SignUp(ctx context.Context, in *SignUpRequest, opts ...grpc.CallOption) (*SignUpResponse, error)
	SignIn(ctx context.Context, in *SignInRequest, opts ...grpc.CallOption) (*SignInResponse, error)
	SignOut(ctx context.Context, in *SignOutRequest, opts ...grpc.CallOption) (*SignOutResponse, error)
	Viewer(ctx context.Context, in *ViewerRequest, opts ...grpc.CallOption) (*ViewerResponse, error)
	GetUserById(ctx context.Context, in *GetUserByIdRequest, opts ...grpc.CallOption) (*GetUserByIdResponse, error)
	UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) SignUp(ctx context.Context, in *SignUpRequest, opts ...grpc.CallOption) (*SignUpResponse, error) {
	out := new(SignUpResponse)
	err := c.cc.Invoke(ctx, "/microservices.user.UserService/SignUp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) SignIn(ctx context.Context, in *SignInRequest, opts ...grpc.CallOption) (*SignInResponse, error) {
	out := new(SignInResponse)
	err := c.cc.Invoke(ctx, "/microservices.user.UserService/SignIn", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) SignOut(ctx context.Context, in *SignOutRequest, opts ...grpc.CallOption) (*SignOutResponse, error) {
	out := new(SignOutResponse)
	err := c.cc.Invoke(ctx, "/microservices.user.UserService/SignOut", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Viewer(ctx context.Context, in *ViewerRequest, opts ...grpc.CallOption) (*ViewerResponse, error) {
	out := new(ViewerResponse)
	err := c.cc.Invoke(ctx, "/microservices.user.UserService/Viewer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetUserById(ctx context.Context, in *GetUserByIdRequest, opts ...grpc.CallOption) (*GetUserByIdResponse, error) {
	out := new(GetUserByIdResponse)
	err := c.cc.Invoke(ctx, "/microservices.user.UserService/GetUserById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error) {
	out := new(UpdateUserResponse)
	err := c.cc.Invoke(ctx, "/microservices.user.UserService/UpdateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	SignUp(context.Context, *SignUpRequest) (*SignUpResponse, error)
	SignIn(context.Context, *SignInRequest) (*SignInResponse, error)
	SignOut(context.Context, *SignOutRequest) (*SignOutResponse, error)
	Viewer(context.Context, *ViewerRequest) (*ViewerResponse, error)
	GetUserById(context.Context, *GetUserByIdRequest) (*GetUserByIdResponse, error)
	UpdateUser(context.Context, *UpdateUserRequest) (*UpdateUserResponse, error)
}

// UnimplementedUserServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (*UnimplementedUserServiceServer) SignUp(ctx context.Context, req *SignUpRequest) (*SignUpResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignUp not implemented")
}
func (*UnimplementedUserServiceServer) SignIn(ctx context.Context, req *SignInRequest) (*SignInResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignIn not implemented")
}
func (*UnimplementedUserServiceServer) SignOut(ctx context.Context, req *SignOutRequest) (*SignOutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignOut not implemented")
}
func (*UnimplementedUserServiceServer) Viewer(ctx context.Context, req *ViewerRequest) (*ViewerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Viewer not implemented")
}
func (*UnimplementedUserServiceServer) GetUserById(ctx context.Context, req *GetUserByIdRequest) (*GetUserByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserById not implemented")
}
func (*UnimplementedUserServiceServer) UpdateUser(ctx context.Context, req *UpdateUserRequest) (*UpdateUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUser not implemented")
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_SignUp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignUpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).SignUp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/microservices.user.UserService/SignUp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).SignUp(ctx, req.(*SignUpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_SignIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignInRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).SignIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/microservices.user.UserService/SignIn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).SignIn(ctx, req.(*SignInRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_SignOut_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignOutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).SignOut(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/microservices.user.UserService/SignOut",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).SignOut(ctx, req.(*SignOutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_Viewer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ViewerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Viewer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/microservices.user.UserService/Viewer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Viewer(ctx, req.(*ViewerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetUserById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUserById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/microservices.user.UserService/GetUserById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUserById(ctx, req.(*GetUserByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/microservices.user.UserService/UpdateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UpdateUser(ctx, req.(*UpdateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "microservices.user.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SignUp",
			Handler:    _UserService_SignUp_Handler,
		},
		{
			MethodName: "SignIn",
			Handler:    _UserService_SignIn_Handler,
		},
		{
			MethodName: "SignOut",
			Handler:    _UserService_SignOut_Handler,
		},
		{
			MethodName: "Viewer",
			Handler:    _UserService_Viewer_Handler,
		},
		{
			MethodName: "GetUserById",
			Handler:    _UserService_GetUserById_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _UserService_UpdateUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "microservices/user/user.proto",
}
