// Code generated by protoc-gen-go. DO NOT EDIT.
// source: echo.proto

package echopb // import "github.com/vvakame/til/appengine/go111-internal-grpc/echopb"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SayRequest struct {
	MessageId            string   `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	MessageBody          string   `protobuf:"bytes,2,opt,name=message_body,json=messageBody,proto3" json:"message_body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SayRequest) Reset()         { *m = SayRequest{} }
func (m *SayRequest) String() string { return proto.CompactTextString(m) }
func (*SayRequest) ProtoMessage()    {}
func (*SayRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_echo_93abddc76aa72704, []int{0}
}
func (m *SayRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SayRequest.Unmarshal(m, b)
}
func (m *SayRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SayRequest.Marshal(b, m, deterministic)
}
func (dst *SayRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SayRequest.Merge(dst, src)
}
func (m *SayRequest) XXX_Size() int {
	return xxx_messageInfo_SayRequest.Size(m)
}
func (m *SayRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SayRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SayRequest proto.InternalMessageInfo

func (m *SayRequest) GetMessageId() string {
	if m != nil {
		return m.MessageId
	}
	return ""
}

func (m *SayRequest) GetMessageBody() string {
	if m != nil {
		return m.MessageBody
	}
	return ""
}

type SayResponse struct {
	MessageId            string               `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	MessageBody          string               `protobuf:"bytes,2,opt,name=message_body,json=messageBody,proto3" json:"message_body,omitempty"`
	Received             *timestamp.Timestamp `protobuf:"bytes,3,opt,name=received,proto3" json:"received,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *SayResponse) Reset()         { *m = SayResponse{} }
func (m *SayResponse) String() string { return proto.CompactTextString(m) }
func (*SayResponse) ProtoMessage()    {}
func (*SayResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_echo_93abddc76aa72704, []int{1}
}
func (m *SayResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SayResponse.Unmarshal(m, b)
}
func (m *SayResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SayResponse.Marshal(b, m, deterministic)
}
func (dst *SayResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SayResponse.Merge(dst, src)
}
func (m *SayResponse) XXX_Size() int {
	return xxx_messageInfo_SayResponse.Size(m)
}
func (m *SayResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SayResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SayResponse proto.InternalMessageInfo

func (m *SayResponse) GetMessageId() string {
	if m != nil {
		return m.MessageId
	}
	return ""
}

func (m *SayResponse) GetMessageBody() string {
	if m != nil {
		return m.MessageBody
	}
	return ""
}

func (m *SayResponse) GetReceived() *timestamp.Timestamp {
	if m != nil {
		return m.Received
	}
	return nil
}

func init() {
	proto.RegisterType((*SayRequest)(nil), "echo.SayRequest")
	proto.RegisterType((*SayResponse)(nil), "echo.SayResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// EchoClient is the client API for Echo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EchoClient interface {
	Say(ctx context.Context, in *SayRequest, opts ...grpc.CallOption) (*SayResponse, error)
}

type echoClient struct {
	cc *grpc.ClientConn
}

func NewEchoClient(cc *grpc.ClientConn) EchoClient {
	return &echoClient{cc}
}

func (c *echoClient) Say(ctx context.Context, in *SayRequest, opts ...grpc.CallOption) (*SayResponse, error) {
	out := new(SayResponse)
	err := c.cc.Invoke(ctx, "/echo.Echo/Say", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EchoServer is the server API for Echo service.
type EchoServer interface {
	Say(context.Context, *SayRequest) (*SayResponse, error)
}

func RegisterEchoServer(s *grpc.Server, srv EchoServer) {
	s.RegisterService(&_Echo_serviceDesc, srv)
}

func _Echo_Say_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EchoServer).Say(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/echo.Echo/Say",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EchoServer).Say(ctx, req.(*SayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Echo_serviceDesc = grpc.ServiceDesc{
	ServiceName: "echo.Echo",
	HandlerType: (*EchoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Say",
			Handler:    _Echo_Say_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "echo.proto",
}

func init() { proto.RegisterFile("echo.proto", fileDescriptor_echo_93abddc76aa72704) }

var fileDescriptor_echo_93abddc76aa72704 = []byte{
	// 305 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x90, 0xb1, 0x4e, 0xf3, 0x30,
	0x14, 0x85, 0x95, 0xb6, 0xfa, 0xf5, 0xd7, 0xed, 0x40, 0xb3, 0x50, 0x45, 0x20, 0x4a, 0xa6, 0x0a,
	0xa9, 0xb6, 0x52, 0x24, 0x06, 0x10, 0x4b, 0x11, 0x03, 0x42, 0x62, 0x68, 0x99, 0x58, 0xd0, 0x4d,
	0x72, 0x71, 0x2d, 0x1a, 0x5f, 0x13, 0xbb, 0x91, 0xb2, 0xb2, 0xf0, 0x00, 0x3c, 0x1a, 0xaf, 0xc0,
	0x83, 0xa0, 0x3a, 0x2d, 0xb0, 0xb3, 0xd9, 0xe7, 0x1c, 0x1d, 0x9d, 0xef, 0x32, 0x86, 0xd9, 0x92,
	0xb8, 0x29, 0xc9, 0x51, 0xd8, 0xd9, 0xbc, 0xa3, 0x03, 0x49, 0x24, 0x57, 0x28, 0xc0, 0x28, 0x01,
	0x5a, 0x93, 0x03, 0xa7, 0x48, 0xdb, 0x26, 0x13, 0x1d, 0x6d, 0x5d, 0xff, 0x4b, 0xd7, 0x4f, 0xc2,
	0xa9, 0x02, 0xad, 0x83, 0xc2, 0x34, 0x81, 0xf8, 0x8e, 0xb1, 0x05, 0xd4, 0x73, 0x7c, 0x59, 0xa3,
	0x75, 0xe1, 0x21, 0x63, 0x05, 0x5a, 0x0b, 0x12, 0x1f, 0x55, 0x3e, 0x0c, 0x46, 0xc1, 0xb8, 0x3b,
	0xef, 0x6e, 0x95, 0x9b, 0x3c, 0x3c, 0x66, 0xfd, 0x9d, 0x9d, 0x52, 0x5e, 0x0f, 0x5b, 0x3e, 0xd0,
	0xdb, 0x6a, 0x33, 0xca, 0xeb, 0xf8, 0x2d, 0x60, 0x3d, 0x5f, 0x68, 0x0d, 0x69, 0x8b, 0x7f, 0x6f,
	0x0c, 0xcf, 0xd8, 0xff, 0x12, 0x33, 0x54, 0x15, 0xe6, 0xc3, 0xf6, 0x28, 0x18, 0xf7, 0xa6, 0x11,
	0x6f, 0xa8, 0xf8, 0x8e, 0x8a, 0xdf, 0xef, 0xa8, 0xe6, 0xdf, 0xd9, 0xe9, 0x2d, 0xeb, 0x5c, 0x67,
	0x4b, 0x0a, 0xaf, 0x58, 0x7b, 0x01, 0x75, 0xb8, 0xc7, 0xfd, 0xe9, 0x7e, 0x60, 0xa3, 0xc1, 0x2f,
	0xa5, 0x59, 0x1b, 0xef, 0xbf, 0x7e, 0x7c, 0xbe, 0xb7, 0x06, 0x71, 0x5f, 0x54, 0x89, 0xd8, 0xb8,
	0xc2, 0x42, 0x7d, 0x1e, 0x9c, 0xcc, 0x2e, 0x1f, 0x2e, 0xa4, 0x72, 0xcb, 0x75, 0xca, 0x33, 0x2a,
	0x44, 0x55, 0xc1, 0x33, 0x14, 0x28, 0x9c, 0x5a, 0x09, 0x30, 0x06, 0xb5, 0x54, 0x1a, 0x85, 0xa4,
	0x24, 0x49, 0x26, 0x4a, 0x3b, 0x2c, 0x35, 0xac, 0x26, 0xb2, 0x34, 0x99, 0xef, 0x30, 0x69, 0xfa,
	0xcf, 0x2f, 0x3d, 0xfd, 0x0a, 0x00, 0x00, 0xff, 0xff, 0x81, 0x27, 0x19, 0xc9, 0xbf, 0x01, 0x00,
	0x00,
}
