name: try environment protection rules
on:
  push:
    paths:
      - 'github/github-actions-envprotection/**'
jobs:
  build:
    name: try environment protection rules
    environment:
      name: temp-20210510
      url:  https://github.com/vvakame/til/pull/58
    runs-on: ubuntu-latest
    steps:
    - run: echo "echo ${{ secrets.TEMP_20210510 }}."
