name: try environment protection rules
on:
  push:
    paths:
      - 'github/github-actions-envprotection/**'
jobs:
  build:
    name: try environment protection rules
    runs-on: ubuntu-latest
    steps:
    - run: echo "echo ${{ env.TEMP_20210510 }}."
